### PR TITLE
Improve usage notes and detect when DMG is not absolute

### PR DESCRIPTION
**Pull request by fgeorges**

### CODE REVIEW

**Comment by jmakeig** [comment]
I think this is a good stop-gap, but I'd much prefer an actual fix to the problem. I think the issue is that the [`cd` to the `versions` directory](https://github.com/withjam/mlvm/blob/master/mlvm.sh#L56) changes the working directory. Thus a relative path to the `.dmg` is resolved against `versions` and not the working directory from which the script was run. I tinkered with it a while back, but wasn’t able to figure it out with my weak bash skillz.

**Comment by fgeorges** [comment]
When I saw in another ticket that you said it would require deep changes, I did not even consider it and just added this (temporary?) check.

Of course, supporting relative paths would be better, but if it is not going to be today, this check is worth merging then, I'd say (besides the improved embedded usage notes).

**Comment by fgeorges** [comment]
By reviewing the code carefully, I could not find any place where the current directory was used.  So this last commit "fixes" the problem by getting rid of the `cd $SOURCE/versions`.

All accesses to versions seem to use `$SOURCE/versions` properly.  But I cannot guarantee I did not miss one, and I did not try all possible commands.  It works for install though.

It is a (very) bad idea to change the PWD in a shell script, so it must be worth getting rid of it anyway.

**Comment by fgeorges** [comment]
Oops, sorry, I missed the dependency on PWD being the versions directory in "list".  It is fixed in the last commit.  This is most likely why there was a cd actually.  The command "use" is tested as well.

**Pull request merged**
